### ISSUE TITLE
Document Common Form Submit Use Case

### ISSUE THREAD

**Issue by mcordingley** [JonDum/ThatValidator#1]
I'm running into a tricky situation with the validation library. I'm trying to validate a form before submitting it, but `validator.isValid()` keeps returning false. After some debugging, it appears that the count of valid fields is zero. This count increments each time I blur from a valid field. So, I decided to call `validator.validate()` in the form submit handler to force a validation pass before checking `validator.isValid()`. Unfortunately, this does not appear to work. My best guess from reading the source is that the validations (all of mine are synchronous) may yet be happening asynchronously.

I want to be able to bind to the form submit event, check the validity of the form, and then prevent the form submit event if the form is not valid. I suspect that this is a common way people would intend to use this library, but cannot figure out how to get it to work.

Some official documentation regarding this behavior of `isValid` and how to only allow valid forms to submit would answer not only my questions, but I'm sure those of many else who try to use this library.

Thanks!

**Comment by maxkorp** [comment]
Flawless timing! We're just shifting around ownership over this library internally, so i'm not totally familiar yet. Give me a little bit to go through everything and see what I can going for you.

**Comment by sarendipitee** [comment]
@mcordingley ThatVal does indeed lack documentation on these methods. Right now `.validate(callback)` is completely async, so I totally agree it's a little inconvenient if you only need synchronous validations. It uses Promises internally, so I'm not sure how to go about making a synchronous version of `.validate()` right now. 

As for `.isValid()`, it returns the immediate validity before the validations have run. This is definitely confusing. Would it be less so if `.isValid()` forced a run through of the validations before return a value?

Calling `.isValid()` inside the callback of `.validate()` should work though.

```
validator.validate(function(isValid) {
   if(isValid)
      //do something
  else
      //do something else
})
```

**Comment by mcordingley** [comment]
Hi guys,

Thanks for the quick response! I think that `isValid` makes much more sense returning the form's current validity (as in, run all of the validations and then return boolean).

The hitch to checking `isValid` in the `validate` callback is that I have to synchronously prevent the submit event from happening. There has to be some way to bind to the submit event, run the validations, and then submit the form if valid (so this can be asynchronous) without getting an infinite loop of validation. ;)

I've been trying to come up with a clean way to do that for a long while now. I can do a quick hack with a boolean in closure scope, but would prefer to avoid that if at all possible. This seems out of scope for the library, but perhaps some clever function writing and an example in the documentation can at least get people rolling.

My code:

```
var validator = new ThatValidator('#signup', config);

$('#signup').submit(function(event) {
    validator.validate(); // Trying to force a validation, here.

    // Want to make sure that the form can only submit if valid.
    if (!validator.isValid()) {
        //console.log(validator.validFields.length + ' fields valid out of ' + validator.fields.length);
        event.preventDefault();
    }
});
```

**Comment by sarendipitee** [comment]
Would something like this work? 

``` javascript
         $('#signup').submit(function(e)  {

             if(validator.isValid())
                 return;

             e.preventDefault()

             validator.validate(function(isValid) {

                if(isValid)
                    $('#signup').submit()

             }, true);

         });
```

I generally never use forms' `submit` event for javascript powered forms. So this may be a bit roundabout, but should work.

**Comment by mcordingley** [comment]
Yeah, actually, that would. It avoids the infinite loop. and is probably about as compact as we could hope for. This and some documentation on specifically what's going on with the named functions would be the additions to the documentation requested. I'll go ahead and drop this into my project. Thanks.

**Comment by sarendipitee** [comment]
Ok. I've added a bit better Docs/Usage to my fork here: https://github.com/JonDum/ThatValidator
